### ISSUE TITLE
Duplicate colors issue

### ISSUE THREAD

**Issue by Stevod** [Linusnie/blender-plots#2]
When I run your code verbatim:
---------------------------------------------------
import numpy as np
import blender_plots as bplt
n, l = 150, 100
x, y = np.meshgrid(np.linspace(0, l, n), np.linspace(0, l, n))
x, y = x.ravel(), y.ravel()

z = np.sin(2*np.pi * x / l)*np.sin(2*np.pi * y / l) * 20
bplt.Scatter(x, y, z, color=(1, 0, 0), name="red")

z = np.sin(4*np.pi * x / l)*np.sin(4*np.pi * y / l) * 20 + 40
bplt.Scatter(x, y, z, color=(0, 0, 1), name="blue")
----------------------------------------------------

I now get this error:

Error: Python: Traceback (most recent call last):
  File "\Text", line 8, in <module>
TypeError: Scatter.__init__() got multiple values for argument 'color'

This persists across a complete uninstall and reinstall of both blender and blender-plots, so it may have been introduced in fixing an earlier issue last week.

**Comment by Linusnie** [comment]
hi, the x, y, z input format was added today, so you probably just need to download and install the latest version. Or use the old example code which stacks x, y, z into a single array: 

```
n, l = 150, 100
x, y = np.meshgrid(np.linspace(0, l, n), np.linspace(0, l, n))
z = np.sin(2 * np.pi * x / l) * np.sin(2 * np.pi * y / l) * 20
bplt.Scatter(np.stack([x, y, z], axis=-1).reshape(-1, 3), color=(1, 0, 0), name="red")
z = np.sin(4 * np.pi * x / l) * np.sin(4 * np.pi * y / l) * 20 + 40
bplt.Scatter(np.stack([x, y, z], axis=-1).reshape(-1, 3), color=(0, 0, 1), name="blue")
```

**Comment by Stevod** [comment]
Thanks for responding out of hours. 

I've reinstalled your new version from github and used your new code, but still getting the same error, unfo.

**Comment by Linusnie** [comment]
hmm, to check that it was updated correctly, could you try running `print(bplt.__file__)` and check if the path it prints has the new version of the code? If there's an older version somewhere it might be loading that instead

**Comment by Stevod** [comment]
I have reverted to Blender 3.1.2 from 3.2 and it has fixed the problem and I can new use your latest add-on version with no probs. The same thing happened a couple of weeks ago and I fixed it by reverting to 3.1.2 so it looks as though  v3.2's API may have changed enough to no longer work your add-on, unfo.

ps the add-on is great, and just what's needed for scietific visualisation :)

**Comment by Linusnie** [comment]
yeah I just tried as well and it doesn't work on 3.2, I'll upgrade eventually but until then 3.1.2 is the only supported version

For reference I'm getting this error with blender 3.2

```
Error: Python: Traceback (most recent call last):
  File "/Text", line 8, in <module>
  File "/home/linus/.config/blender/3.2/scripts/addons/blender-plots-main/blender_plots/scatter.py", line 48, in __init__
    self.marker_modifier = add_mesh_markers(
  File "/home/linus/.config/blender/3.2/scripts/addons/blender-plots-main/blender_plots/scatter.py", line 201, in add_mesh_markers
    modifier.node_group.inputs.new("NodeSocketMaterial", "Point Color")  # Input_2
AttributeError: 'NoneType' object has no attribute 'inputs'
```

glad to hear you're using the addon :) I'm very curious to see what people make with it

**Comment by Stevod** [comment]
That's the same error I'm getting, so that is consistant. I'll stick with 3.1.2 for now.

Thanks,
David

**Comment by Linusnie** [comment]
Turned out to be an easy fix, should now work with blender 3.2 as of https://github.com/Linusnie/blender-plots/commit/c02cf28978a653710079b143fea06e471155f5d6!
